### ISSUE TITLE
Think of a good actual name for the extension

### ISSUE THREAD

**Issue by Ellpeck** [flowr-analysis/vscode-flowr#24]
Potentially "flowR for VSCode"? Or something? @EagleoutIce your input on this would be great obviously

**Comment by EagleoutIce** [comment]
I think, given it's current capabilities, 'R Slicer' would be a better name. Maybe `R Slicer (with flowR)` so that searching for flowR yields it as well?

**Comment by Ellpeck** [comment]
What about `flowR R Slicer`? that way we don't have to have parentheses in the name
